// Vapid keys
exports.publicVapidKey = 'BCgHUWcopIA9e2zrvMmISx3sYXS4JdwLr_sC8PS80BULQmmGgnQQUnA0VOKD-UeRDk7jUUEBBzVmz6POMMJYgfM'
exports.privateVapidKey = '6OzqHC3J9x9zANj_qGNUQ0Xu6DMUMGAzhArKxnMrcpE'